# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10_xF69UZrJnoKGhu4FITzsNnW50nrmyP
"""

import numpy as np

print('hello')

!git clone https://github.com/AugeosRnD/prova.git